### ISSUE TITLE
Cifs format has lat lon coordinate order vs lon lat in geojson

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/tilelive-cifs#1]
According to https://developers.google.com/waze/data-feed/road-closure-information the lat/lon is used as ordering vs lon/lat as currently implemented by us. This should be switched to comply with the standard

**Comment by leonardehrenfried** [comment]
You're totally right. This is an oversight and must be fixed.

Which order does the sharedstreets tool output?

How could we migrate this? I suggest the following: 

- In DT1 we keep everything as is
- We create a new file with the correct coordinate order for DT2
- I change this map layer to swap the coordinates
- Client code can also stay the same

WDYT?

**Comment by leonardehrenfried** [comment]
This has been fixed in https://github.com/stadtnavi/tilelive-cifs/commit/628c6eb1093ac576fe8ad164188560264837f3fe
