### ISSUE TITLE
New feature: Support additional roadworks layer

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/tilelive-cifs#2]
We want to support multiple cifs-sources, like e.g. the manually updated one of the city of Herrenberg, as well as the road administrations' DATEX2 feed transformed into cifs (preview here: https:data.mfdz.de/mfdz/cifs_arbeitsstellen_svz_bw/body.json).

**Comment by leonardehrenfried** [comment]
Shouldn't the JSON array be the value of the top level property `incidents`?

**Comment by hbruch** [comment]
Yes, indeed. File is updated

**Comment by leonardehrenfried** [comment]
This has been implemented in https://github.com/stadtnavi/tilelive-cifs/commit/043c1c4d70e0a8739a8495b600fa5ee249eeb993
